export * from './bet-competition/bet-competition.mutations'
export * from './bet-competition/bet-competition.queries'
export * from './bet/bet.mutations'
export * from './bet/bet.queries'
export * from './fixture/fixture.queries'
export * from './user/user.queries'
