@baseUrl = http://localhost:3001/external


### Fetch and insert Leagues, Team, Fixtures for single season
## params - leagueId, season
POST {{baseUrl}}/init-leagues
Content-Type: application/json

{
  "leagueIds": [15],
  "season": 2025
}

### Fetch and insert Leagues, Team, Fixtures for single season
## need to have the league-data.ts file set
## params - season
POST {{baseUrl}}/init-supported-leagues
Content-Type: application/json

{
  "season": 2025
}


### Fetch leagues
## params - leagueId, season
GET {{baseUrl}}/leagues
Content-Type: application/json

{
  "leagueId": 32,
  "season": 2024
}

### Fetch and insert league
## params - leagueId, season
POST {{baseUrl}}/insert-league
Content-Type: application/json

{
  "leagueId": 15,
  "season": 2025
}

### Fetch teams
## params - leagueId, season
POST {{baseUrl}}/teams
Content-Type: application/json

{
  "season": 2025,
  "leagueId": 140
}

### Fetch and insert teams
## params - leagueId, season, leagueId
POST {{baseUrl}}/insert-teams
Content-Type: application/json

{
  "leagueId": 15,
  "season": 2025,
  "leagueId": "d6dd86cb-6a43-4587-9472-b5b863e1f454"
}

### Fetch fixtures
## params - leagueIds, ?season, ?dateFrom, ?dateTo
POST {{baseUrl}}/fixtures
Content-Type: application/json

{
  "leagueIds": [39],
  "season": 2024,
  "dateFrom": "2024-08-10",
  "dateTo": "2024-09-03"
}

### Fetch and insert fixtures
## params - leagueIds, ?season, ?dateFrom, ?dateTo
POST {{baseUrl}}/insert-fixtures
Content-Type: application/json

{
  "leagueIds": [39],
  "season": 2025,
  "dateFrom": "2025-08-01",
  "dateTo": "2025-08-19"
}

### Fetch players squads
## params - leagueIds
POST {{baseUrl}}/players-squads-by-league
Content-Type: application/json

{
  "leagueIds": [39]
}

### Fetch players squads
## params - teamIds
POST {{baseUrl}}/players-squads
Content-Type: application/json

{
  "teamIds": [35],
  "season": 2025
}

### Fetch and insert players
## params - leagueIds, teamIds, season
POST {{baseUrl}}/insert-players
Content-Type: application/json

{
  "season": 2025,
  "leagueIds": [39]
}

### Fetch players profiles
## params - playerIds
POST {{baseUrl}}/player-profiles
Content-Type: application/json

{
  "playerIds": [526535]
}

### Fetch player fixture stats
## params - fixtureIds
POST {{baseUrl}}/fetch-player-fixture-stats
Content-Type: application/json

{
  "fixtureIds": [1208022,1208036,1208047]
}

### Fetch and insert player fixture stats
## params - fixtureIds
POST {{baseUrl}}/insert-player-fixture-stats
Content-Type: application/json

{
  "fixtureIds": [1208022,1208036,1208047]
}

### Fetch player season statistics
POST {{baseUrl}}/fetch-player-season-statistics
Content-Type: application/json

{
  "playerIds": [306],
  "seasons": [2023, 2024]
}


### Fetch and insert player season statistics
POST {{baseUrl}}/insert-player-season-statistics
Content-Type: application/json

{
  "playerIds": [306],
  "seasons": [2023, 2024]
}