@baseUrl = http://localhost:3001/external

### Fetch leagues
## params - externalLeagueId, season
GET {{baseUrl}}/leagues
Content-Type: application/json

{
  "externalLeagueId": 32,
  "season": 2024
}

### Fetch and insert leagues
## params - externalLeagueId, season
POST {{baseUrl}}/insert-leagues
Content-Type: application/json

{
  "externalLeagueId": 32,
  "season": 2024
}

### Fetch teams
## params - externalLeagueId, season
GET {{baseUrl}}/teams
Content-Type: application/json

{
  "externalLeagueId": 32,
  "season": 2024,
  "leagueId": "dfa327c4-c847-4420-bfdb-3921d11d7b5c"
}

### Fetch and insert teams
## params - externalLeagueId, season, leagueId
POST {{baseUrl}}/insert-teams
Content-Type: application/json

{
  "externalLeagueId": 15,
  "season": 2025,
  "leagueId": "76a08ec0-cb96-41e2-84ec-079b3fd894aa"
}

### Fetch fixtures
## params - externalLeagueIds, ?season, ?dateFrom, ?dateTo
GET {{baseUrl}}/fixtures
Content-Type: application/json

{
  "externalLeagueIds": [32],
  "season": 2024,
  "dateFrom": "2025-06-07",
  "dateTo": "2025-06-07"
}

### Fetch and insert fixtures
## params - externalLeagueIds, ?season, ?dateFrom, ?dateTo
POST {{baseUrl}}/insert-fixtures
Content-Type: application/json

{
  "externalLeagueIds": [15],
  "season": 2025,
  "dateFrom": "2025-06-06",
  "dateTo": "2025-06-30"
}


