@baseUrl = http://localhost:3001/jobs

### Daily data update
GET {{baseUrl}}/daily-data-update
Content-Type: application/json

### Regular data update
GET {{baseUrl}}/regular-data-update
Content-Type: application/json


### Regular data update POST
POST {{baseUrl}}/regular-data-update
Content-Type: application/json

{
  "season": 2025,
  "selectedDate": "2025-08-25"
}