@baseUrl = http://localhost:3001/mock


### Create bet competitions
POST {{baseUrl}}/bet-competitions
Content-Type: application/json

{
  "userId": "3cdab61f-408e-4ffc-b7b6-e3be5e86e997",
  "externalLeagueIds": [39],
  "season": 2024,
  "name": "Test Competition",
  "deletePrevious": true
}

### Create bets
POST {{baseUrl}}/bets
Content-Type: application/json

{
  "userId": "3cdab61f-408e-4ffc-b7b6-e3be5e86e997",
  "dateFrom": "2025-04-02",
  "dateTo": "2025-05-31",
  "deletePreviousBets": true,
  "betCompetitionId": "dbe668bc-aa18-49ab-92fe-49141579dbbc"
}

