@baseUrl = http://localhost:3001/mock


### Create bet competitions
POST {{baseUrl}}/bet-competitions
Content-Type: application/json

{
  "leagueIds": [39, 345],
  "season": 2025,
  "name": "Test Competition",
  "deletePrevious": true
}

### Create bets
POST {{baseUrl}}/bets
Content-Type: application/json

{
  "dateFrom": "2025-06-02",
  "dateTo": "2025-07-30",
  "deletePreviousBets": true,
  "betCompetitionId": "430c0490-2f3d-4c43-81de-f5582affd1c5"
}

### Test
GET {{baseUrl}}/test
Content-Type: application/json