@baseUrl = http://localhost:3001/player-season-stats

### Get player season stats
POST {{baseUrl}}/player-season-stats
Content-Type: application/json

{
  "season": 2025,
  "leagueIds": [39]
}

### Create player season stats
POST {{baseUrl}}/create-player-season-stats
Content-Type: application/json

{
  "season": 2024,
  "dateFrom": "2024-08-21",
  "dateTo": "2024-08-26"
}