@baseUrl = http://localhost:3001/seed

### Initialize database fully
# csv files are required for tables below
# User, UserSettings, League, Nation, Season, Team
POST {{baseUrl}}/init-all-tables-from-csv
Content-Type: application/json

{
   "seasons": [2025],
   "fixtureExternalLeagueIds": [15],
   "fixtureDateFrom": "2025-06-01",
   "fixtureDateTo": "2025-07-31",
   "shouldMockBetData": true
}

### Seed initial data for specific tables from csv files
# Options: League, Nation, Season
POST {{baseUrl}}/init-specific-tables-from-csv
Content-Type: application/json

{
   "tablesWithoutRelations": ["Season"],
   "seasons": [2025]
}

### Seed all data from external API
# User, UserSettings, Season and Nation must be provided from csv files
POST {{baseUrl}}/init-all-from-external-api
Content-Type: application/json

{
   "seasons": [2024,2025],
   "dateFrom": "2025-08-01",
   "dateTo": "2026-06-30"
}

### Initialize Database
# This endpoint initializes the database schema
POST {{baseUrl}}/init-database
Content-Type: application/json

### Initialize Users with Settings
# meant for User and UserSettings only
POST {{baseUrl}}/init-users
Content-Type: application/json

{} 


