@baseUrl = http://localhost:3001/seed

### Initialize database fully
# csv files are required for tables below
# User, UserSettings, League, Nation, Season
POST {{baseUrl}}/init-all
Content-Type: application/json

{
   "tablesWithoutRelations": ["Season", "League", "Nation"],
   "tablesWithRelations": ["Team"],
   "seasons": [2024,2025],
   "fixtureExternalLeagueIds": [15,345],
   "fixtureDateFrom": "2024-07-01",
   "fixtureDateTo": "2025-07-31",
   "shouldMockCustomData": true
}

### Initialize Database
# This endpoint initializes the database schema
POST {{baseUrl}}/init-database
Content-Type: application/json

### Initialize Users with Settings
# meant for User and UserSettings only
POST {{baseUrl}}/init-users
Content-Type: application/json

{}

### Seed initial data for specific tables from csv files
# Options: League, Nation, Season
POST {{baseUrl}}/seed-from-csv
Content-Type: application/json

{
   "tablesWithoutRelations": ["Season"],
   "seasons": [2025]
}

### Seed initial data for specific tables from external API
POST {{baseUrl}}/seed-from-external-api
Content-Type: application/json

{
   "seasons": [2025],
   "dateFrom": "2024-07-01",
   "dateTo": "2025-06-30"
}