import { FederationType, OrganizationType } from '@packages/types'

export type SupportedLeague = Record<
  string,
  {
    id: number
    name: string
    type: 'Cup' | 'League'
    variant: 'nation' | 'club'
    seasons: number[]
    federation: FederationType
    organization: OrganizationType
    disabled?: boolean
  }[]
>

export const supportedLeagues: SupportedLeague = {
  International: [
    {
      id: 1,
      name: 'World Cup',
      type: 'Cup',
      variant: 'nation',
      federation: FederationType.WORLD,
      organization: OrganizationType.FIFA,
      seasons: [2022],
      disabled: true,
    },
    {
      id: 4,
      name: 'Euro Championship',
      type: 'Cup',
      variant: 'nation',
      federation: FederationType.EUROPE,
      organization: OrganizationType.UEFA,
      seasons: [2024],
    },
    {
      id: 19,
      name: 'Africa Cup of Nations',
      type: 'Cup',
      variant: 'nation',
      federation: FederationType.AFRICA,
      organization: OrganizationType.CAF,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 7,
      name: 'Asian Cup',
      type: 'Cup',
      variant: 'nation',
      federation: FederationType.ASIA,
      organization: OrganizationType.AFC,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 9,
      name: 'Copa America',
      type: 'Cup',
      variant: 'nation',
      federation: FederationType.SOUTH_AMERICA,
      organization: OrganizationType.CONMEBOL,
      seasons: [2024],
    },
    {
      id: 22,
      name: 'CONCACAF Gold Cup',
      type: 'Cup',
      variant: 'nation',
      federation: FederationType.NORTH_CENTRAL_AMERICA,
      organization: OrganizationType.CONCACAF,
      disabled: true,
      seasons: [2023],
    },
    {
      id: 5,
      name: 'UEFA Nations League',
      type: 'League',
      variant: 'nation',
      federation: FederationType.EUROPE,
      organization: OrganizationType.UEFA,
      seasons: [2024],
    },
  ],
  World: [
    {
      id: 15,
      name: 'FIFA Club World Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.WORLD,
      organization: OrganizationType.FIFA,
      seasons: [2023],
    },
    {
      id: 10,
      name: 'International Friendlies',
      type: 'League',
      variant: 'nation',
      federation: FederationType.WORLD,
      organization: OrganizationType.FIFA,
      seasons: [2023, 2024],
    },
  ],
  Europe: [
    {
      id: 2,
      name: 'UEFA Champions League',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.UEFA,
      seasons: [2023, 2024],
    },
    {
      id: 3,
      name: 'UEFA Europa League',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.UEFA,
      seasons: [2023, 2024],
    },
    {
      id: 848,
      name: 'UEFA Europa Conference League',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.UEFA,
      seasons: [2023, 2024],
    },
    {
      id: 531,
      name: 'UEFA Super Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.UEFA,
      seasons: [2023, 2024],
    },
  ],
  England: [
    {
      id: 39,
      name: 'Premier League',
      type: 'League',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.ENGLAND,
      seasons: [2023, 2024],
    },
    {
      id: 45,
      name: 'FA Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.ENGLAND,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 48,
      name: 'League Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.ENGLAND,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 528,
      name: 'Community Shield',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.ENGLAND,
      seasons: [2023],
      disabled: true,
    },
  ],
  Germany: [
    {
      id: 78,
      name: 'Bundesliga',
      type: 'League',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.GERMANY,
      seasons: [2023, 2024],
    },
    {
      id: 81,
      name: 'DFB Pokal',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.GERMANY,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 529,
      name: 'Germany Super Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.GERMANY,
      seasons: [2023],
      disabled: true,
    },
  ],
  Spain: [
    {
      id: 140,
      name: 'La Liga',
      type: 'League',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.SPAIN,
      seasons: [2023, 2024],
    },
    {
      id: 143,
      name: 'Copa del Rey',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.SPAIN,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 556,
      name: 'Spain Super Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.SPAIN,
      seasons: [2023],
      disabled: true,
    },
  ],
  Italy: [
    {
      id: 135,
      name: 'Serie A',
      type: 'League',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.ITALY,
      seasons: [2023, 2024],
    },
    {
      id: 137,
      name: 'Coppa Italia',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.ITALY,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 547,
      name: 'Italy Super Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.ITALY,
      seasons: [2023],
      disabled: true,
    },
  ],
  France: [
    {
      id: 61,
      name: 'Ligue 1',
      type: 'League',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.FRANCE,
      seasons: [2023, 2024],
    },
    {
      id: 66,
      name: 'Coupe de France',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.FRANCE,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 526,
      name: 'France Super Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.FRANCE,
      seasons: [2023],
      disabled: true,
    },
  ],
  Portugal: [
    {
      id: 94,
      name: 'Primeira Liga',
      type: 'League',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.PORTUGAL,
      seasons: [2023, 2024],
    },
    {
      id: 96,
      name: 'Taça de Portugal',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.PORTUGAL,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 97,
      name: 'Taça da Liga',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.PORTUGAL,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 550,
      name: 'Portugal Super Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.PORTUGAL,
      seasons: [2023],
      disabled: true,
    },
  ],
  Netherlands: [
    {
      id: 88,
      name: 'Eredivisie',
      type: 'League',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.NETHERLANDS,
      seasons: [2023, 2024],
    },
    {
      id: 90,
      name: 'KNVB Beker',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.NETHERLANDS,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 543,
      name: 'Netherlands Super Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.NETHERLANDS,
      seasons: [2023],
      disabled: true,
    },
  ],
  Belgium: [
    {
      id: 144,
      name: 'Jupiler Pro League',
      type: 'League',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.BELGIUM,
      seasons: [2023, 2024],
    },
    {
      id: 147,
      name: 'Belgium Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.BELGIUM,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 519,
      name: 'Belgium Super Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.BELGIUM,
      seasons: [2023],
      disabled: true,
    },
  ],
  Austria: [
    {
      id: 218,
      name: 'Bundesliga',
      type: 'League',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.AUSTRIA,
      seasons: [2023, 2024],
    },
    {
      id: 220,
      name: 'Austria Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.AUSTRIA,
      seasons: [2023],
      disabled: true,
    },
  ],
  Turkey: [
    {
      id: 203,
      name: 'Super Lig',
      type: 'League',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.TURKEY,
      seasons: [2023, 2024],
    },
    {
      id: 206,
      name: 'Turkey Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.TURKEY,
      seasons: [2023],
      disabled: true,
    },
    {
      id: 551,
      name: 'Turkey Super Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.TURKEY,
      seasons: [2023],
      disabled: true,
    },
  ],
  Czechia: [
    {
      id: 345,
      name: 'Fortuna Liga',
      type: 'League',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.CZECH,
      seasons: [2023, 2024],
    },
    {
      id: 347,
      name: 'MOL Cup',
      type: 'Cup',
      variant: 'club',
      federation: FederationType.EUROPE,
      organization: OrganizationType.CZECH,
      seasons: [2023],
      disabled: true,
    },
  ],
}
