const fs = require('fs')
const path = require('path')

const generatedFilePath = path.resolve(__dirname, '../src/generated.types.ts')
const databaseFilePath = path.resolve(__dirname, '../src/database.types.ts')

const warningComment = `/**
 * WARNING: This file is automatically generated by kysely-codegen.
 * DO NOT modify this file directly.
 */

`

const content = fs.readFileSync(generatedFilePath, 'utf8')

fs.writeFileSync(generatedFilePath, warningComment + content)

const tableRegex = /export interface (\w+) {([^}]+)}/g
const tables = []
let match

while ((match = tableRegex.exec(content)) !== null) {
  const tableName = match[1]
  if (tableName !== 'DB' && tableName !== 'Generated' && tableName !== 'Timestamp') {
    tables.push(tableName)
  }
}

function createDatabaseTypesFile(tables) {
  let content = `/**
 * This file exports database types with Selectable, Insertable, and Updateable wrappers.
 * These types are derived from the generated types.
 */

import type { Selectable, Insertable, Updateable } from 'kysely'
import type { DB } from './generated.types'

`

  tables.forEach(table => {
    content += `export type ${table} = Selectable<DB['${table}']>\n`
    content += `export type Insert${table} = Insertable<DB['${table}']>\n`
    content += `export type Update${table} = Updateable<DB['${table}']>\n\n`
  })

  return content
}

const databaseTypesContent = createDatabaseTypesFile(tables)
fs.writeFileSync(databaseFilePath, databaseTypesContent)

console.log('Types generated successfully, now building them...')
